# Generated by Django 3.2.20 on 2023-08-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1', 'paintings'), ('2', 'models and sculptures'), ('3', 'street art'), ('4', 'other')], default=1, max_length=25),
        ),
    ]
